[window]
opacity = 0.8
padding.x = 8
padding.y = 10

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12

[colors.primary]
background = "#2d353b"
foreground = "#d3c6aa"

# Everforest color scheme
[colors.normal]
black = "#232a2e"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"

[colors.bright]
black = "#3d484d"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"
